---
- name: Converge
  hosts: all
  roles:
    - role: grp
      vars:
        # postgres
        grp_deploy_postgres: true
        grp_postgres_db: "grp"
        grp_postgres_user: "grp"
        # django
        grp_django_system_group: "www-data"
        grp_django_recreate_virtual_env: true
        grp_django_system_user_home: "/home/{{ grp_django_system_user }}"
        grp_django_codebase_path: "{{ grp_django_system_user_home }}/app"
        grp_django_versioned_path: "{{ grp_django_codebase_path }}-versioned"
        grp_frontend_app_path: "{{ grp_django_codebase_path}}/frontend"
        grp_frontend_app_path_local: "~/Code/Ona/grp-frontend/build"
        grp_django_checkout_path: "{{ grp_django_versioned_path }}/{{ ansible_date_time['epoch'] }}"
        grp_django_venv_path: "{{ grp_django_system_user_home }}/.virtualenvs/{{ grp_django_system_user }}"
        grp_requirements_paths:
          - "{{ grp_django_checkout_path }}/requirements/dev.txt"
        grp_django_celery_app: "api"
        grp_django_python_source_version: "3.6"
        grp_django_python_version: "python3.6"
        grp_django_enable_celery: true
        grp_django_local_settings_path: "{{ grp_django_checkout_path }}/api/config/settings.py"
        grp_django_app_settings_module: "api.config.settings"
        grp_django_wsgi_module: "api.config.wsgi:application"
        grp_manage_services: True
        grp_django_service_name: "{{ grp_django_system_user }}"
        grp_django_service_type: "notify"
        grp_django_service_restart: "on-failure"
        grp_django_service_group: "{{ grp_django_system_group }}"
        grp_django_service_unit_after: "network.target"
        grp_django_service_install_wantedby: "multi-user.target"
        grp_django_pid_socks_dir: "/var/run/{{ grp_django_service_name }}"
        grp_django_wsgi_socket: "{{ grp_django_pid_socks_dir }}/{{ grp_django_system_user }}.sock"
        grp_django_proxy_read_timeout: "300s"
        grp_django_settings_template_path: "templates/grp/local_settings.py.j2"
        grp_docs_path: "{{ grp_django_checkout_path }}/api/static/docs"
        grp_django_static_path: "/home/{{ grp_django_system_user }}/static"
        grp_django_media_path: "/home/{{ grp_django_system_user }}/media"
        grp_django_init_commands:
          - check
          - migrate --no-input
        grp_django_pip_packages:
          - celery
          - uwsgi
          - redis>3
          - django-debug-toolbar
        grp_django_celeryd_nodes: "default-node"
        grp_django_celeryd_opts: "--time-limit=300 --concurrency=8"
        grp_django_app_settings:
          SECRET_KEY: "'{{ vault_django_secret_key }}'"
          SITE_ID: 1
          DATABASES: |
            {
                'default': {
                    'ENGINE': 'django.contrib.gis.db.backends.postgis',
                    'NAME': '{{ grp_postgres_db }}',
                    'USER': '{{ grp_postgres_user }}',
                    'PASSWORD': '{{ vault_postgres_password }}',
                    'HOST': '{{ grp_postgres_host }}'
                }
            }
          STATICFILES_DIRS: |
            (
                os.path.join(BASE_DIR, "static"),
            )
          CACHES: |
            {
              'default': {
                  'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
                  'LOCATION': '/var/tmp/grp-stage/grp_django_cache',
                  'TIMEOUT': 86400,
                  'OPTIONS': {
                      'MAX_ENTRIES': 1000
                  }
              }
            }

          STATIC_URL: "'/static/'"
          MEDIA_ROOT: "'{{ grp_django_media_path }}'"
          ROOT_URLCONF: "'api.config.urls'"
          MEDIA_URL: "'/media/'"
          EMAIL_USE_TLS: True
          EMAIL_HOST: "'smtp.mailgun.org'"
          EMAIL_PORT: "587"
          EMAIL_HOST_USER: "'{{ vault_smtp_login }}'"
          EMAIL_HOST_PASSWORD: "'{{ vault_smtp_password }}'"
          DEFAULT_FROM_EMAIL: "'grp <techops+grp@ona.io>'"
          ONA_BASE_URL: "'https://api.ona.io'"
          ONA_USERNAME: "'grptest'"
          ONA_ORG_NAME: "'grp'"
          ONA_PASSWORD: "'{{ vault_ona_password }}'"
          ONA_CROSS_AUTHENTICATION_URL: "'https://api.ona.io/api/v1/user'"
          ALLAUTH_ONA_BASE_URL: "'https://api.ona.io'"
          ONA_MEMBERS_TEAM_ID: 3381
          BROKER_URL: "'redis://localhost:6379/0'"
          CELERY_RESULT_BACKEND: "'redis://localhost:6379/0'"
          WHITENOISE_KEEP_ONLY_HASHED_FILES: True
          ALLOWED_HOSTS: "[
                                  '{{ grp_nginx_site_names[0] }}',
                                  '127.0.0.1',
                                ]"
          CORS_ORIGIN_WHITELIST: |
            (
                "{{ grp_nginx_site_names[0] }}",
            )

          DEBUG: False
          AUTO_CREATE_SUBMISSION_WEBHOOKS: False
          AUTO_CREATE_FILTERED_DATASETS: False
          INSTALLED_APPS: "[
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'rest_framework',
            'django_filters',
            'corsheaders',
            'oauth2_provider',
            'reversion',
            'rest_framework.authtoken',
            'rest_auth',
            'raven.contrib.django.raven_compat',
            'api.users',
            'api.roles',
            'api.initial_data',
            'api.utils',
            'api.common',
            'api.box',
            'api.forms',
            ]"
          PERMISSIONS: |
            (
               ('report_on_solutions', 'Can report on solutions'),
               ('view_collected_data', 'Can view the collected Data in Ona'),
               ('form_creation', 'Can create a form in Ona'),
               ('view_reporting_forms', 'Can view the form templates'),
               ('excel_import_data', 'Can import data in Ona'),
               ('view_indicator_dashboard', 'Can view the indicators dashboard'),
               ('view_indicator_table', 'Can view the indicators table'),
               ('open_indicator_dashboard', 'Can open indicators in Canopy'),
               ('build_indicator_dashboard', 'Can build indicators in canopy'),
               ('access_to_box', 'Can access box.com'),
               ('view_download_public_documents', 'Can view and download public documents'),
               ('search_project_solution', 'Can search solutions'),
               ('submit_solution', 'Can submit solution'),
               ('approve_reject_solution', 'Can approve or reject solution'),
               ('view_approved_project_solution', 'Can view approved projects'),
               ('view_rejected_project_solution', 'Can view rejected solutions'),
               ('publish_solution_on_social_media', 'Can publish solution in social media'),
               ('user_creation', 'Can manage users'),
               ('user_permissions', 'Can manage roles and permissions'),
            )
          SOLUTION_THEMES: |
            (
              ('agriculture', 'Agriculture'),
              ('community', 'Community'),
              ('education', 'Education'),
              ('energy', 'Energy'),
              ('environment', 'Environment'),
              ('financialservices', 'Financial Services'),
              ('genderequity', 'Gender Equity'),
              ('general', 'General'),
              ('health', 'Health'),
              ('humanitarian', 'Humanitarian'),
              ('humanrights', 'Human Rights'),
              ('livelihood', 'Livelihood'),
              ('poverty', 'Poverty'),
              ('shelter', 'Shelter'),
              ('water', 'Water'),
            )
          SOLUTION_PARTNERS: |
            (
              ('WFP', 'World Food Programme'),
              ('CARE', ' Cooperative for Assistance and Relief Everywhere'),
              ('OXFARM', ' Oxfam International'),
              ('IFRC', 'International Federation of Red Cross and Red Crescent Societies'),
              ('AAH', 'Action Against Hunger'),
              ('RI', 'Refugees International'),
              ('IMF', 'International Monetary Fund'),
            )
          FILE_UPLOAD_TYPES: |
            (('image', 'Image'), ('document', 'Document'))
          ALLOWED_FILE_EXTENSIONS: |
            (
              ('png', 'PNG'),
              ('jpeg', 'JPGEG'),
              ('pdf', 'PDF'),
              ('txt', 'TXT'),
            )
          LOGIN_REDIRECT_URL: "'/'"
          EMAIL_BACKEND: "'django.core.mail.backends.smtp.EmailBackend'"
          FRONTEND_URL: "'http: //localhost: 3000/'"
          REST_SESSION_LOGIN:  True
          ACCOUNT_EMAIL_REQUIRED:  False
          ACCOUNT_AUTHENTICATION_METHOD: "'username'"
          ACCOUNT_EMAIL_VERIFICATION: "'optional'"
          PASSWORD_RESET_TIMEOUT_DAYS: "1"
          RAVEN_CONFIG: |
            {
              'dsn': '{{ vault_grp_sentry_dsn }}',
              'release': raven.fetch_git_sha(os.path.dirname(os.pardir)),
            }
          MAP_USER_TO_ONA: True
          USE_DEFAULT_PASSWORD: True  # This is just for testing
          DEFAULT_PASSWORD: "'password'"
          ONA_SETTINGS: |
            {
              'URLS': {
                'profiles': 'https://stage-api.ona.io/api/v1/profiles',
                'users': 'https://stage-api.ona.io/api/v1/users',
                'orgs': 'https://stage-api.ona.io/api/v1/orgs',
                'token_url': 'https://stage-api.ona.io/o/token/',
                'dataviews': 'https://stage-api.ona.io/api/v1/dataviews/',
              },
              'TOKEN': '7c8d9d70b3e8dd89f61bc1eff5808fe9a165f5af',
              'GRP_ORG_NAME': 'grp_test',
              'OAUTH': {'client_id': 'GRP', 'client_secret': 'GRP'},
              }
          BOX_SETTINGS: |
            {
              'boxAppSettings':{
                'clientID':'',
                'clientSecret':'',
                'appAuth':{'publicKeyID':'', 'privateKey':'', 'passphrase':''},
              },
              'enterpriseID':'',
              'BOX_PUBLIC_USER_ID':'',
            }
          ONA_FORMS_URLS: |
            {
              'round_1':'https://stage.ona.io/grp_god_user/407/930/webform',
              'round_2':'https://stage.ona.io/grp_god_user/407/962/webform',
              'solution_template':'https://stage.ona.io/grp_mel/409/1018/webform',
              'round_1_submissions_zebra':'https://stage.ona.io/grp_god_user/407/930#/table',
              'round_2_submissions_zebra':'https://stage.ona.io/grp_god_user/407/962#/table',
              'solutions_submissions_zebra':'https://stage.ona.io/grp_god_user/407/1018#/table',
              'round_1_submissions_api':'https://stage-api.ona.io/api/v1/data/930?query=&sort=%7B%22_submission_time%22%3A1%7D',
              'round_2_submissions_api':'https://stage-api.ona.io/api/v1/data/962?start=0&limit=100&sort=%7B%22_submission_time%22%3A1%7D&query=',
              'solutions_submissions_api':'https://stage-api.ona.io/api/v1/data/1018',
              'solutions_submissions_form_api':'https://stage-api.ona.io/api/v1/forms/1018',
              'round_1_submissions_data_import':'https://stage.ona.io/grp_god_user/407/930#/overview',
              'round_2_submissions_data_import':'https://stage.ona.io/grp_god_user/407/962#/overview',
              'solutions_submissions_data_import':'https://stage.ona.io/grp_mel/407/1018#/overview',
              'form_authoring':'https://stage.ona.io/grp_mel/407',
              'project':'https://stage-api.ona.io/api/v1/projects/407'
            }
          WEB_SOCKET_PORT: "8765"
          OAUTH_REDIRECT_URL: "'https://grp.stage.ona.io/api/v1/login/'"
          GRP_COOKIE_LENGTH: "50"
          GRP_COOKIE_AUTH_HEADER: "'GRPAUTH'"
          OAUTH_CLIENT_ID: "'{{ vault_oauth_client_id }}'"
          OAUTH_CLIENT_SECRET: "'{{ vault_oauth_client_secret }}'"
          OAUTH_FE_REDIRECT_URL: "'https://grp.stage.ona.io/login/'"
          AUTHENTICATION_BACKENDS: "'api.common.authentication.OnadataBackend'"
          SESSION_COOKIE_NAME: "'sessionid'"
          FORMS_LABEL_NAMES_MAP: |
            {
              'title': 'qn01',
              'theme': 'qn02',
              'region': 'qn04',
              'country': 'qn06',
              'partner': 'qn07'
              }
          MIDDLEWARE: "[
           'corsheaders.middleware.CorsMiddleware',
           'django.middleware.common.CommonMiddleware',
           'django.middleware.security.SecurityMiddleware',
           'django.contrib.sessions.middleware.SessionMiddleware',
           'django.middleware.common.CommonMiddleware',
           'django.middleware.csrf.CsrfViewMiddleware',
           'django.contrib.auth.middleware.AuthenticationMiddleware',
           'django.contrib.messages.middleware.MessageMiddleware',
           'django.middleware.clickjacking.XFrameOptionsMiddleware',
           'reversion.middleware.RevisionMiddleware',
           ]"
          TEMPLATES: "[
            {
              'BACKEND': 'django.template.backends.django.DjangoTemplates',
              'DIRS': [os.path.join(BASE_DIR, 'templates')],
              'APP_DIRS': True,
              'OPTIONS': {
                'context_processors': [
                  'django.template.context_processors.debug',
                  'django.template.context_processors.request',
                  'django.contrib.auth.context_processors.auth',
                  'django.contrib.messages.context_processors.messages',
                  'api.common.settings_in_templates.settings_in_templates',
                ]
              },
            }
            ]"
          WSGI_APPLICATION: "'api.config.wsgi.application'"
          AUTH_PASSWORD_VALIDATORS: "[
            {
              'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
            },
            {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
            {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
            {
              'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'
            },
          ]"
          LANGUAGE_CODE: "'en-us'"
          TIME_ZONE: "'UTC'"
          USE_I18N: True
          USE_L10N: True
          USE_TZ: True
          AUTH_USER_MODEL: "'users.GrpUser'"
          REST_FRAMEWORK: |
            {
              'PAGE_SIZE': 10,
              'EXCEPTION_HANDLER': 'rest_framework_json_api.exceptions.exception_handler',
              'DEFAULT_PAGINATION_CLASS': 'api.utils.pagination.GrpPagination',
              'DEFAULT_PARSER_CLASSES': (
                                          'rest_framework_json_api.parsers.JSONParser',
                                          'rest_framework.parsers.FormParser',
                                          'rest_framework.parsers.MultiPartParser',
                                          'rest_framework.parsers.JSONParser',
              ),
              'DEFAULT_RENDERER_CLASSES': (
                                            'rest_framework_json_api.renderers.JSONRenderer',
                                            'rest_framework.renderers.JSONRenderer',
                                            'rest_framework.renderers.BrowsableAPIRenderer',
              ),
              'DEFAULT_METADATA_CLASS': 'rest_framework_json_api.metadata.JSONAPIMetadata',
              'DEFAULT_FILTER_BACKENDS': (
                                           'rest_framework.filters.OrderingFilter',
                                           'django_filters.rest_framework.DjangoFilterBackend',
                                           'rest_framework.filters.SearchFilter',
              ),
              'SEARCH_PARAM': 'search',
              'TEST_REQUEST_RENDERER_CLASSES': (
                                                 'rest_framework_json_api.renderers.JSONRenderer',
              ),
              'TEST_REQUEST_DEFAULT_FORMAT': 'vnd.api+json',
              'DEFAULT_PERMISSION_CLASSES': ('api.common.permissions.GRPPermissions',),
              'DEFAULT_AUTHENTICATION_CLASSES': (
                                                  'api.utils.authentication.CsrfExemptSessionAuthentication',
                                                  'api.common.authentication.OnadataBackend',
              ),
            }
          OAUTH2_PROVIDER: |
            {
             'SCOPES': {
               'read': 'Read scope',
               'write': 'Write scope',
               'groups': 'Access to your groups',
             }
            }
          MAX_PAGE_SIZE: "'100'"


        grp_django_git_url: "git@github.com:onaio/grp-backend.git"
        grp_django_git_version: "'{{ vault_grp_django_git_version }}'"
        grp_django_grp_use_regular_old_pip: false
        grp_django_grp_use_pipenv: true
        grp_django_system_wide_dependencies:
          - build-essential
          - git
          - python3.6-dev
          - binutils
          - libproj-dev
          - gdal-bin
          - python-gdal
          - libgeoip1
          - python3-distutils
          - libpq-dev

        grp_django_top_python_statements:
          - import os
          - import raven
          - from celery.schedules import crontab
          - BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
          ## python statements included at the bottom of settings file
        grp_django_bottom_python_statements:
          - CSRF_TRUSTED_ORIGINS = CORS_ORIGIN_WHITELIST

        # react
        grp_react_system_user: "{{ grp_django_system_user }}"
        grp_react_system_group: "{{ grp_django_system_group }}"
        grp_react_system_user_home: "/home/{{ grp_django_system_user }}/react"
        grp_react_system_wide_dependencies:
          - git
          - nodejs
          - yarn
        grp_react_codebase_path: "{{ grp_react_system_user_home }}/app"
        grp_react_versioned_path: "{{ grp_react_codebase_path }}-versioned"
        grp_react_node_version: "10.x"
        grp_react_git_url: "git@github.com:onaio/grp-frontend.git"
        grp_react_git_version: "'{{ vault_grp_react_git_version }}'"
        grp_react_git_key: "{{ grp_django_git_key }}"
        grp_react_git_key_ssh_file: "{{ grp_django_git_key_ssh_file }}"
        grp_react_git_key_filename: "{{ grp_django_git_key_filename }}"
        grp_react_remove_git_key: True
        grp_react_app_settings:
          REACT_APP_WEBSITE_NAME: "{{ grp_django_system_user }}"
          REACT_APP_ENDPOINT: "http://127.0.0.1:8888/api/v1"
          GENERATE_SOURCEMAP: false
          REACT_APP_ONA_WEBSITE: 'https://stage.ona.io/'
        # nginx
        grp_nginx_site_names:
          - "grp.stage.ona.io"
        kaznet_nginx_www_site_names:
          - "www.grp.stage.ona.io"
